### ISSUE TITLE
Readme & How to install

### ISSUE THREAD

**Issue by wlfbck** [M3wM3w/ComfyFactorio#1]
Hey,

if you could add a Readme.md with a "how to install" that would be great :)

**Comment by xxalfa** [comment]
For Windows Steam:
* [CMD] + [R] then write **%appdata%/Factorio/**
* In the folder **scenarios** comes the unzipped ZIP.
* In the **control.lua** you determine which map should be loaded.
* Then you start the game and select the scenario.
* If you started the scenario, you can save it, now there is a new ZIP in the **saves** folder.

**Comment by xxalfa** [comment]
A feedback, if the installation worked, would be nice? To enjoy the scenario with others, the operation of a headless server is recommended.

**Comment by klugemonkey** [comment]
Is there any way to generate the save file using the command line instead of the Client?  Seems that when I try from the command line, the center of the map is generated prior to the scenario loading using defaults.  Tried both using the --map2scenario scenario option and the --start-server-load-scenario scenario option.
